services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env  # Ensure this path is correct
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend  # Path to the frontend folder
    ports:
      - "8501:8501"  # Map Streamlit's port
    volumes:
      - ./frontend:/app
    depends_on:
      - backend  # Ensure the backend starts first
